syntax = "proto3";

package wendycloud.v1;

import "google/protobuf/empty.proto";
import "google/protobuf/timestamp.proto";

service TeamService {
  rpc CreateTeam(CreateTeamRequest) returns (Team);
  rpc GetTeam(GetTeamRequest) returns (Team);
  rpc UpdateTeam(UpdateTeamRequest) returns (Team);
  rpc DeleteTeam(DeleteTeamRequest) returns (google.protobuf.Empty);
  rpc ListTeams(ListTeamsRequest) returns (stream ListTeamsResponse);
  rpc AddTeamMember(AddTeamMemberRequest) returns (TeamMember);
  rpc RemoveTeamMember(RemoveTeamMemberRequest) returns (google.protobuf.Empty);
  rpc ListTeamMembers(ListTeamMembersRequest) returns (stream ListTeamMembersResponse);
}

message Team {
  string id = 1;
  string organization_id = 2;
  string name = 3;
  optional string description = 4;
  google.protobuf.Timestamp created_at = 5;
  google.protobuf.Timestamp updated_at = 6;
}

message TeamMember {
  string id = 1;
  string team_id = 2;
  string user_id = 3;
  google.protobuf.Timestamp created_at = 4;
}

message CreateTeamRequest {
  string organization_id = 1;
  string name = 2;
  optional string description = 3;
}

message GetTeamRequest {
  string id = 1;
  string organization_id = 2;
}

message UpdateTeamRequest {
  string id = 1;
  string organization_id = 2;
  optional string name = 3;
  optional string description = 4;
}

message DeleteTeamRequest {
  string id = 1;
  string organization_id = 2;
}

message ListTeamsRequest {
  string organization_id = 1;
}

message ListTeamsResponse {
  Team team = 1;
}

message AddTeamMemberRequest {
  string team_id = 1;
  string organization_id = 2;
  string user_id = 3;
}

message RemoveTeamMemberRequest {
  string team_id = 1;
  string organization_id = 2;
  string user_id = 3;
}

message ListTeamMembersRequest {
  string team_id = 1;
  string organization_id = 2;
}

message ListTeamMembersResponse {
  TeamMember member = 1;
}
